### ISSUE TITLE
toctree not taken info account

### ISSUE THREAD

**Issue by keesj** [Arello-Mobile/sphinx-confluence#17]
When running *make singlehtml*

I am getting the following output
```
Running Sphinx v1.7.4
WARNING: while setting up extension sphinx_confluence: directive 'toctree' is already registered, it will be overridden
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [singlehtml]: all documents
updating environment: 11 added, 0 changed, 0 removed
reading sources... [100%] scope                                  
```

The result for me is that only the main page it taken into account for the content generation and that the toctree is not taken into account. 

My setup (normally) uses the sphinx_rdt_theme

**Comment by keesj** [comment]
I found https://github.com/tonybaloney/sphinxcontrib-confluencebuilder to work well for me.

**Comment by spyoungtech** [comment]
Toctree is overridden with the directive that produces confluence TOC macro. Also take a look at #13 which mentions a workaround for your problem.
