### ISSUE TITLE
Example on how to import resultant docs to Confluence

### ISSUE THREAD

**Issue by SimplicityGuy** [Arello-Mobile/sphinx-confluence#4]
It would be nice to have an example on how to upload or import the resultant docs into Confluence. The documentation around importing documents in the Confluence Storage Format seem scarce.

**Comment by n-elloco** [comment]
You can use [confluence_publisher](https://github.com/Arello-Mobile/confluence-publisher) tool

**Comment by SimplicityGuy** [comment]
Awesome! Thanks for pointing to that tool.

**Comment by ssbarnea** [comment]
I opened #7 before seeing this bug. 

I think it would be recommended to include this critical missing information in the project README.
