### ISSUE TITLE
Doesn't support automodule

### ISSUE THREAD

**Issue by oweizman** [Arello-Mobile/sphinx-confluence#5]
Docs that use automodule aren't currently supported. I get the following error: ERROR: Unknown directive type "automodule".

**Comment by ikeeip** [comment]
I think you forget about `sphinx.ext.autodoc` while configuring your project. Just add it in your build configuration file `conf.py`:

```
extensions = ['sphinx_confluence', 'sphinx.ext.autodoc']
```

Enjoy!
