### ISSUE TITLE
Installation instructions should use sphinx_confluence instead of just confluence

### ISSUE THREAD

**Issue by chadmv** [Arello-Mobile/sphinx-confluence#6]
The installation instructions should say:

```
extensions. = ['sphinx_confluence']
html_translator_class = 'sphinx_confluence.HTMLConfluenceTranslator'
```

instead of 

```
extensions. = ['confluence']
html_translator_class = 'confluence.HTMLConfluenceTranslator'
```

**Comment by ssbarnea** [comment]
In fact it doesn't work with either of them and I find the main readme from PYPI extreamly confusing. 

One thing is clear, installing with pip works and you endup with a python module named `sphinx_confluence`. You can easily test this by doing a `import sphinx_confluence`.

Still this does not enable you in any way to use it as a Sphinx extension. Also I don't really see any point in documenting the alteration of the sys.path when you are supposed to install modules using pip. 

Altering sys.path is one of the worst anti-patterns in Python, let's get rid of it, please.

**Comment by ikeeip** [comment]
Thanks for comments. I update code on github to v0.0.3 and added some information about usage to README.md. But I don't have time to update PYPI now. I will try to make it on the week.

**Comment by ikeeip** [comment]
New version 0.0.3 is available on [pypi](https://pypi.python.org/pypi/sphinx-confluence)
