### ISSUE TITLE
document uploading to confluence

### ISSUE THREAD

**Issue by ssbarnea** [Arello-Mobile/sphinx-confluence#7]
While this module converts Sphinx documentation into so called internal storage format used by Confluence its readme page is missing to give any information regarding how someone would be able to upload these to Confluence (preferably in a an automated way).

**Comment by ikeeip** [comment]
Hi, you can either use Confluence REST API for it or check [confluence-publisher](https://github.com/Arello-Mobile/confluence-publisher) tool from our Documentarion Toolkit. I added information about it to README.md
